on:
  push:
    branches: [main, develop]
    paths:
      - "client/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client/

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
      - name: Build
        run: npm run build
